### ISSUE TITLE
FLV6 Support 

### ISSUE THREAD

**Issue by fm-sys** [cyberman54/Forumslader-Companion#7]
Hi, thanks for your great work! 

Does this IQ app support the new FLV6 meanwhile? I'm asking cause I'm wondering whether I want to buy a FLV6 for my bike setup... 

Thanks for the info.

**Comment by cyberman54** [comment]
Yes, it does, but not with the current available firmware of FLV6. There is an update necessary for FLV6, which is still due, but announced by the makers of FLV6.

**Comment by cyberman54** [comment]
Today i received the information that an update of FLV6 firmware was published, which should work this Forumslader Companion software. I will test this soon to confirm.

**Comment by cyberman54** [comment]
Issue solved with [release 1.3.2](https://github.com/cyberman54/Forumslader-Companion/releases/tag/1.3.2)
/cc @fm-sys

**Comment by fm-sys** [comment]
Great, thanks!
